# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjJmMmVjMmUxMGQ0MmQ0NzcyMjMwOWQ2MzM2MDY0MzViMGUwMzI3ZmJmNTc4N2U4MmNlOWY2NTkwOGY2YWM1ZTc5YjIyYzhmMzE1NDcxZDdjZTk1N2JlNmVkNTg2MWZlMzY5YWZkNzIwYTEzMWExM2VlOWVkYjdlZGQ5NTYxYmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
